png("plot3.png", width=480, height=480)
plot(strptime(dsubset$Datetime, "%d/%m/%Y %H:%M:%S"), dsubset$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(strptime(dsubset$Datetime, "%d/%m/%Y %H:%M:%S"), dsubset$Sub_metering_2, type = "l", col="red")
lines(strptime(dsubset$Datetime, "%d/%m/%Y %H:%M:%S"), dsubset$Sub_metering_3, type = "l", col="blue")
legend("topright",lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))