png("plot4.png", width=480, height=480)
par(mfcol = c(2,2))
plot(strptime(dsubset$Datetime, "%d/%m/%Y %H:%M:%S"), dsubset$Global_active_power, type="l", xlab="",ylab="Global Active Power(Kilowatts)" )
plot(strptime(dsubset$Datetime, "%d/%m/%Y %H:%M:%S"), dsubset$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(strptime(dsubset$Datetime, "%d/%m/%Y %H:%M:%S"), dsubset$Sub_metering_2, type = "l", col="red")
lines(strptime(dsubset$Datetime, "%d/%m/%Y %H:%M:%S"), dsubset$Sub_metering_3, type = "l", col="blue")
legend("topright",lty=1, col=c("black", "red", "blue"), legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(strptime(dsubset$Datetime, "%d/%m/%Y %H:%M:%S"), dsubset$Voltage, type = "l", xlab = "datetime", ylab = "Voltage")
plot(strptime(dsubset$Datetime, "%d/%m/%Y %H:%M:%S"), dsubset$Global_reactive_power, type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()